#!/system/xbin/sh
	echo '255' > /sys/class/leds/blue/brightness
	echo '255' > /sys/class/leds/red/brightness
	echo '255' > /sys/class/leds/green/brightness
	/system/bin/charger
	cat /dev/input/event1 > /dev/keycheck&
	sleep 3
	kill -9 $!
	if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
	then
	# fixing CPU clocks to avoid issues in recovery
	echo 1024000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
	echo 245000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
	rm /cache/recovery/boot
	# remount rootfs rw
	mount -o remount,rw rootfs /

	# Umount MTDs
	# umount -l /dev/block/mtdblock1
	# umount -l /dev/block/mtdblock2
	# umount -l /dev/block/mtdblock3
	umount -l /data/idd
	umount -l /cache
	umount -l /data

	# Mount recovery partition
	cd /
	rm -r /sbin /sdcard
	rm -f etc init.* uevent* default*
	if [ -f /system/bin/recovery.tar ]
	then
		tar -xf /system/bin/recovery.tar
	fi

	# Umount /system
	# umount -l /dev/block/mtdblock0
	umount -l /system

	# chroot
	echo 1 > /sys/devices/i2c-0/0-0040/leds/lcd-backlight/als/enable
	echo 0 > /sys/class/android_usb/android0/enable
	echo 0fce > /sys/class/android_usb/android0/idVendor 
	echo 6168 > /sys/class/android_usb/android0/idProduct
	echo "mass_storage,adb" > /sys/class/android_usb/android0/functions
	echo 1 > /sys/class/android_usb/android0/enable
	echo '0' > /sys/class/leds/blue/brightness
	echo '0' > /sys/class/leds/red/brightness
	echo '0' > /sys/class/leds/green/brightness
	chroot / /init

	fi

	echo '0' > /sys/class/leds/blue/brightness
	echo '0' > /sys/class/leds/red/brightness
	echo '0' > /sys/class/leds/green/brightness
